apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple
  name: simple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple
  strategy: {}
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - image: mclovin612615/simple:1.0
        name: simple
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: ""
        - name: DB_PORT
          value: ""
        - name: DB_USER
          value: ""
        - name: DB_PASSWORD
          value: ""
        - name: DB_DATABASE
          value: ""
          



